openapi: 3.0.0
info:
    title: TD5 - ingredients
    version: 1.0.0
servers:
  - url: 'http://localhost:8080'
paths:
  /ingredients:
    get:
      responses:
        200:
          description: All the ingredients saved in the db
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Ingredient'
  /ingredients/{id}: 
    get:
      parameters:
        - name : id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Returns the ingredient with the id
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/Ingredient'
        404:
          description: If there isn't an ingredient with this ID then it returns a not found response
          content:
            text/plain:
              example : 
                'The ingredient with the id={id} is not found!'
  /ingredients/{id}/stock:
    get:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
        - name : at
          in: query
          schema:
            type: string
            format: date 
        - name: unit 
          in: query 
          schema:
            $ref: '#/components/schemas/StockValueUnitEnum'
      responses:
        200:
          description: Returns the stock value at the instant and unit given
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StockValue'
        400:
          description: When the required query params are not given
          content:
            text/plain:
              example:
                'Either mandatory query parameter `at` or `unit` is not provided.'
        404:
          description: If there isn't an ingredient with this ID then it returns a not found response
          content:
            text/plain:
              example : 
                'The ingredient with the id={id} is not found!'
  /dishes:
    get:
      responses:
        200:
          description: All the dishes saved in the db
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Dish'
  /dishes/{id}/ingredients:
    put:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Ingredient'
      responses:
        200:
          description: Returns the updated dish
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dish'
        400:
          description: When the required request body is not given
          content:
            text/plain:
              example:
                'The required request body is not provided.'
        404:
          description: If there isn't a dish with this ID then it returns a not found response
          content:
            text/plain:
              example : 
                'The dish with the id={id} is not found!'
components:
  schemas:
    Ingredient:
      properties:
        id:
          type: integer
        name:
          type: string
        price:
          type: number
        category:
          type: string
          enum: [VEGETABLE, ANIMAL, MARINE, DAIRY, OTHER]
        stockMovementList:
          type: array
          items:
            $ref: '#/components/schemas/StockMovement'
    Dish:
      properties:
        id: 
          type: integer
        name:
          type: string
        price:
          type: number
        ingredients:
          type: array
          items:
            $ref: '#/components/schemas/Ingredient'
    StockMovement:
      properties:
        id:
          type: integer
        value:
          $ref: '#/components/schemas/StockValue'
        type:
          $ref: '#/components/schemas/StockMovementTypeEnum'
        creationDatetime:
          type: string
          format: date
          example:
            '2026-04-15T10:00:00Z'
    StockMovementTypeEnum:
      type: string
      enum:
        - IN
        - OUT
    StockValue:
      properties:
        quantity:
          type: number
        unit:
          $ref: '#/components/schemas/StockValueUnitEnum'
    StockValueUnitEnum:
      type: string
      enum:
        - PC 
        - KG 
        - L