spring:
  application:
    name: ingredient-again
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mini-dish-db
    username: postgres
    password: ${DB_PASS}